### ISSUE TITLE
Module Parse Failed 

### ISSUE THREAD

**Issue by mkomod** [Gozala/random-access-idb-mutable-file#3]
Hi, I'm getting the following error

I''ve fixed it by changing package.json

```module: "src/.... ``` to ```module: "lib/...```

but this doesn't seem like a clean fix.

```
 ERROR  Failed to compile with 1 errors                               8:14:59 PM

 error  in ./node_modules/@sammacbeth/random-access-idb-mutable-file/src/random-access-idb-mutable-file.js

Module parse failed: Unexpected token (4:12)
You may need an appropriate loader to handle this file type.
| 
| import RandomAccess from "random-access-storage"
> import type {
|   Stat,
|   Request,

 @ ./node_modules/random-access-web/index.js 38:24-77
 @ ./node_modules/dat-js/index.js
 @ ./src/boot/dat.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
```

package.json

```{
  "name": "qdat",
  "version": "0.0.1",
  "scripts": {
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "dat-js": "^8.0.0",
    "quasar": "^1.0.0-beta.0"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.0-beta.0",
    "devtron": "1.4.0",
    "electron": "4.0.5",
    "electron-debug": "2.1.0",
    "electron-devtools-installer": "2.2.4",
    "strip-ansi": "=3.0.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "resolutions": {
    "ajv": "6.8.1"
  }
}
```

Thanks in advance

**Comment by tmorin** [comment]
Hi all,

As far I understood, the directory _src/_ contains sources wrote with [flow](https://flow.org).

This directory is also exposed (via the field _module_) by _package.json_ as a ES2015 modules according to https://github.com/rollup/rollup/wiki/pkg.module.

That means modern bundler like webpack will in priority load the sources wrote in flow rather than a regular JavaScript files (i.e. _lib/_ directory).

Could it be possible to simply remove the field _module_ in _package.json_ so that project like [dat-js](https://github.com/datproject/dat-js) could be easily bundled?

Best regards
